"""Generates supabase/seed/demo_summaries.sql by running the REAL summary service over the seeded demo data.

    cd backend
    python -m scripts.generate_seed                  # core seed files first
    python -m scripts.generate_summaries_seed        # needs any Postgres you can create databases on

Because the rows come from the same code the app uses, the seeded summaries (observations, action items, goal
progress) can never drift from what the application would generate. Set TEST_ADMIN_DSN (default
postgresql://postgres@localhost:54329/postgres) to point at a scratch server; it creates and drops its own database.
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime
from decimal import Decimal
from pathlib import Path

import psycopg
from psycopg.rows import dict_row

from scripts.generate_seed import ACCOUNT_ID, NS, USER_ID, q

ROOT = Path(__file__).resolve().parents[2]
ADMIN = os.environ.get("TEST_ADMIN_DSN", "postgresql://postgres@localhost:54329/postgres")
SEEDS = ["demo_user", "demo_account", "demo_cycles", "demo_transactions", "demo_goals", "demo_budgets"]


def run(dsn: str, files: list[Path]) -> None:
    with psycopg.connect(dsn, autocommit=True) as c:
        for f in files:
            c.execute(f.read_text(encoding="utf-8"))


def main() -> None:
    base, _, _ = ADMIN.rpartition("/")
    name = "finpilot_summaries_seedgen"
    dsn = f"{base}/{name}"
    with psycopg.connect(ADMIN, autocommit=True) as admin:
        admin.execute(f"drop database if exists {name} with (force)")
        admin.execute(f"create database {name}")
    try:
        run(dsn, [ROOT / "backend" / "tests" / "sql" / "supabase_stub.sql"])
        with psycopg.connect(dsn, autocommit=True) as c:
            c.execute("create publication supabase_realtime")
        run(dsn, sorted((ROOT / "supabase" / "migrations").glob("*.sql")))
        run(dsn, [ROOT / "supabase" / "seed" / f"{s}.sql" for s in SEEDS])

        from app.services.summaries import sync_summaries

        with psycopg.connect(dsn, row_factory=dict_row) as conn:
            sync_summaries(conn, USER_ID, ACCOUNT_ID)
            summaries = conn.execute("select * from monthly_summaries where user_id = %s order by period_start", (USER_ID,)).fetchall()
            actions = conn.execute(
                "select a.* from monthly_summary_actions a join monthly_summaries s on s.id = a.summary_id "
                "where a.user_id = %s order by s.period_start, a.action_key", (USER_ID,)).fetchall()
        if os.environ.get("PREVIEW"):
            last = summaries[-1]
            print(last["title"], "| income", last["income_total"], "| expenses", last["expense_total"], "| savings", last["savings_total"])
            for o in last["content"]["observations"]:
                print("  OBS:", o["text"])
            for a in actions:
                if a["summary_id"] == last["id"]:
                    print(f"  ACTION [{a['priority']}] {a['title']}: {a['description']}")
    finally:
        with psycopg.connect(ADMIN, autocommit=True) as admin:
            admin.execute(f"drop database if exists {name} with (force)")

    sum_id = {str(s["id"]): str(uuid.uuid5(NS, f"summary:{s['financial_cycle_id']}")) for s in summaries}
    srows = []
    for s in summaries:
        sid = sum_id[str(s["id"])]
        srows.append(
            f"  ({q(sid)}, {q(USER_ID)}, {q(str(s['financial_cycle_id']))}, {q(s['title'])}, {q(s['period_start'])}, {q(s['period_end'])}, "
            f"{s['income_total']}, {s['expense_total']}, {s['savings_total']}, {q(s['savings_rate'])}, {q(s['top_category'])}, "
            f"{q(s['previous_cycle_expenses'])}, {q(s['expense_change'])}, {q(s['is_final'])}, {q(json.dumps(s['content'], default=str))}::jsonb, "
            f"{q(s['period_end'])})"
        )
    arows = []
    for a in actions:
        sid = sum_id[str(a["summary_id"])]
        arows.append(
            f"  ({q(str(uuid.uuid5(NS, f'action:{sid}:{a['action_key']}')))}, {q(sid)}, {q(USER_ID)}, {q(a['action_key'])}, {q(a['title'])}, "
            f"{q(a['description'])}, {q(a['priority'])}, {q(a['category'])}, {q(json.dumps(a['evidence'], default=str))}::jsonb, 'OPEN')"
        )

    body = f"""-- demo_summaries.sql
-- Stored monthly summaries for the {len(summaries)} completed demo cycles, with their observations (in `content`) and
-- {len(actions)} data-driven action items. Generated by running the application's own summary service over the demo
-- ledger (scripts/generate_summaries_seed.py), so it always matches what the app would produce.
-- Run AFTER demo_goals.sql (goal progress is part of each summary).

insert into public.monthly_summaries
  (id, user_id, financial_cycle_id, title, period_start, period_end, income_total, expense_total, savings_total,
   savings_rate, top_category, previous_cycle_expenses, expense_change, is_final, content, generated_at)
values
""" + ",\n".join(srows) + """
on conflict (financial_cycle_id) do nothing;

insert into public.monthly_summary_actions
  (id, summary_id, user_id, action_key, title, description, priority, category, evidence, status)
values
""" + ",\n".join(arows) + """
on conflict (summary_id, action_key) do nothing;
"""
    (ROOT / "supabase" / "seed" / "demo_summaries.sql").write_text(body, encoding="utf-8")
    print(f"wrote demo_summaries.sql: {len(summaries)} summaries, {len(actions)} action items")


if __name__ == "__main__":
    main()
